### ISSUE TITLE
项目类型应为共享项目

### ISSUE THREAD

**Issue by telecomadm1145** [SlimeNull/EleCho.Json#5]
项目类型应为共享项目，而非库项目

**Comment by telecomadm1145** [comment]
共享项目虽然会导致编译时间增长，但能确保代码在目标Net版本兼容

**Comment by SlimeNull** [comment]
新的奇妙小玩意儿开发了 (旧的不搞了 (新版本添加了多目标支持, 至少包含 netstandard2.0, net46, net47, net5, net6
