### ISSUE TITLE
JsonData应为结构

### ISSUE THREAD

**Issue by telecomadm1145** [SlimeNull/EleCho.Json#9]
JsonData操作开销较大，使用结构能减少GC带来的开销，可以显著提升性能

**Comment by telecomadm1145** [comment]
这个建议和Issue #2联动

**Comment by SlimeNull** [comment]
新的奇妙小玩意儿开发了 (旧的不搞了 (新的库 JsonData, 例如 JsonObject 直接继承 Dictionary, 序列化的时候操作起来更方便嘞
